# Generated by Django 5.2.8 on 2025-11-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConcertName', models.CharField(max_length=100)),
                ('ConcertDate', models.DateField()),
                ('ConcertTime', models.TimeField()),
                ('ConcertLocation', models.CharField(max_length=100)),
                ('ConcertDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='(Lower value shows first)')),
                ('ticket_label', models.CharField(help_text="This will be the ticket name shown to the audience (i.e. 'Standard Seating' or 'Concession Seating' or 'Restricted View')", max_length=40)),
                ('QtyAvailable', models.IntegerField()),
                ('QtySold', models.IntegerField()),
                ('DisplayTicket', models.BooleanField(default=False, help_text='When ticked, this will show as a purchasable ticket. This should only be false for complimentary tickets.')),
                ('LinkedTickets', models.ManyToManyField(blank=True, help_text='Use this to select which tickets should have their ticket quantities synced.', to='ticketing.tickettype')),
                ('for_concert', models.ForeignKey(default=None, help_text='Please select the matching concert here. Make sure this is selected or the ticket will not show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.concert')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='ConcertTicketTypes',
            field=models.ManyToManyField(blank=True, help_text='Ticket types set to this concert.', to='ticketing.tickettype'),
        ),
    ]
