# Generated by Django 5.2.8 on 2025-11-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='ConcertDate',
            new_name='concert_date',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='ConcertDescription',
            new_name='concert_description',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='ConcertLocation',
            new_name='concert_location',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='ConcertName',
            new_name='concert_name',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='ConcertTicketTypes',
            new_name='concert_ticket_types',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='ConcertTime',
            new_name='concert_time',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='LinkedTickets',
            new_name='linked_tickets',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='DisplayTicket',
            new_name='lisplay_ticket',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='QtyAvailable',
            new_name='qty_available',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='QtySold',
            new_name='qty_sold',
        ),
    ]
