# Generated by Django 5.2.8 on 2025-11-30 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_rename_concertdate_concert_concert_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='lisplay_ticket',
            new_name='display_ticket',
        ),
    ]
