# Generated by Django 5.2.8 on 2025-11-30 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_rename_lisplay_ticket_tickettype_display_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='concert_ticket_types',
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='for_concert',
            field=models.ForeignKey(default=None, help_text='Please select the matching concert here. Make sure this is selected or the ticket will not show.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='ticketing.concert'),
        ),
    ]
