# Generated by Django 5.2.8 on 2025-11-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_remove_concert_concert_ticket_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='qty_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='qty_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
