# Generated by Django 5.2.8 on 2025-11-30 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_tickettype_qty_total_alter_tickettype_qty_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text="Customer's Name", max_length=60)),
                ('email', models.CharField(default='', help_text="Customer's Email", max_length=100)),
                ('transaction_ID', models.CharField(default='', help_text='Autogenerated transaction ID from STRIPE', max_length=100)),
                ('validity', models.BooleanField(default=True, help_text='If ticked, this ticket is valid.')),
                ('change_log', models.TextField(blank=True, default='', help_text='Will log any changes by automatic systems. I recommend adding any changes here if editing manually.')),
                ('for_concert', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.concert')),
                ('ticket_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.tickettype')),
            ],
        ),
    ]
