# Generated by Django 5.2.8 on 2025-11-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='conductor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
