# Generated by Django 5.2.8 on 2025-11-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_concert_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
