# Generated by Django 5.2.8 on 2025-11-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_tickettype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the ticket type.', max_length=100, null=True),
        ),
    ]
