# Generated by Django 5.2.8 on 2025-11-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_tickettype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='price_id',
            field=models.CharField(blank=True, help_text='The price_id generated when creating the price point in stripe.', max_length=100, null=True),
        ),
    ]
