# Generated by Django 5.2.8 on 2025-11-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
