# Generated by Django 5.2.8 on 2025-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='id',
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
