# Generated by Django 5.2.8 on 2025-11-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_remove_committeemember_id_alter_committeemember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
