# Generated by Django 5.2.8 on 2025-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_alter_committeemember_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
