# Generated by Django 5.2.8 on 2025-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_committeemember_id_alter_committeemember_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('conductor', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('programme', models.TextField(blank=True, help_text='List of pieces performed')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concerts/')),
            ],
            options={
                'verbose_name_plural': 'Past Concerts',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/committee/'),
        ),
    ]
