# Generated by Django 5.2.8 on 2025-11-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_pastconcert_alter_committeemember_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastconcert',
            name='image',
        ),
    ]
