# Generated by Django 5.2.8 on 2025-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_remove_pastconcert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastconcert',
            name='date',
            field=models.DateField(help_text='Rough date of concert'),
        ),
    ]
