# Generated by Django 5.2.8 on 2025-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_alter_pastconcert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastconcert',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
